Script started on 2023-03-02 19:27:54-05:00 [TERM="xterm" TTY="/dev/pts/16" COLUMNS="427" LINES="85"]
]0;dxie32@compute:~/cs3340/asn2[?2004h[dxie32@compute asn2]$ date
[?2004lThu Mar  2 07:27:58 PM EST 2023
]0;dxie32@compute:~/cs3340/asn2[?2004h[dxie32@compute asn2]$ who am i
[?2004l]0;dxie32@compute:~/cs3340/asn2[?2004h[dxie32@compute asn2]$ whoami
[?2004ldxie32
]0;dxie32@compute:~/cs3340/asn2[?2004h[dxie32@compute asn2]$ pwd
[?2004l/home/dxie32/cs3340/asn2
]0;dxie32@compute:~/cs3340/asn2[?2004h[dxie32@compute asn2]$ [7m./asn2.sh < girl.img[27m./asn2.sh < girl.img
[?2004l------------- 1 The input binary image -------------
000000000111100000000000000000000000000000000000000000000000000000000110111
111111111000000000000000000000000000000000000000000000000000000000001110001
111111111000000000000000000000000000000000000000000000000000000000001110111
111111110000000000000000000000000000000000000000000000000000000000001110100
111111100000000000000000000000000000000000000000000000000000000000011110111
111111000110000000000000000000000000000000000000000000000000000000011110000
111110001100000000000000000000000000000000000000000000000000000000011110111
011100011000000000000000000000000000000000000000000000000000000000111110101
011000110000000000000000001000000000000000000000000000000000000100111110101
011001100000000000101111000000000000000000000000000000000000011001111110101
011111000010000000001111000001111111100000000000000000000001110001111110111
011111000100000000011111101111111111000000000000000000001111100011111110000
001110000000000000101111111111111110000000000000000000111110000111111110111
001100010000000101111111111111111100000000000000000000111000001111111110001
011100110000000111111111111111111000000000000000000110000000011111111110111
010001110100111111111111111111100000000000000000011100000000111111111110100
010011011101111111111111111110100000000000000000111000000001111111111110111
010010011001111111111111111110100000000000000000111100000011111111111110000
011110110111111111111111111111000000000000000000011110001111111111111100111
011111001111111111111111111111000000000000000000011110001111111111111100001
111111011111111111111111111100000000000000000000011110001111111111111000111
111111111111111111111111110000000000000000000000001111001111111111111000001
111001111111111111111111100000000000000000000000001111001111111111110000111
111001111111111111111011000000000000000000000000001111001111111111110000000
100011111111111111111110000000000000000000000000001111101111111111110000000
100011111111111111111110000000000000000000000000001111101111111111100000000
001111111111111111111010000000010000000000000000001111101111111111100000000
001111111111111111111100000000111110000000000000001111101111111111100000000
011111111111111111110000000000000111100000000000111111100111111111000000000
111111111111111111110000000111111111110000000011111111100111111111000000000
111111111111111111100000001111111111010000000111111111110111111111000000000
111111111111111111000000011111110111110000001111111111110111111110000000000
111111111111111111000000011111110011111000011111011111110111111110000000000
111111111111111110000000111111100001111000010110011111110111111110000000000
111111111111111100000001000111000000111000000000111111110111111100000000000
111110011111111110000010000001100000111000000011111111110111111100000000000
111111011111111100001110000000000000001100000001111111110111111100000000000
111111011111111000011110000000000000001100000000111111110111111100000000000
111110111111110000011110000000000000001100000000111111110011111000000000000
111111101111111000111110000000000000000100000000111111110011111000000000000
111111100111100001111110000000000000000100000000111111110011111000000000000
111111111111110001111110000000000000001100000000011111110011110000000000000
111111101011000011111110000000000000001100000000111111110011110000000000000
111111101111100011111111000000000000001100000000011111110011110000000000000
111110111110000111111111000000000001100100000000111111110011100000000000000
111111111100001111111111000000000001100110000000111111111001100000000000000
111110111100011111111111000000000001111111000000111111111001100000000000000
111111111100011111111111000000000000011110000001111111111001100000000000000
101111100100111111111111100000000000000000000001111111111001000000000000000
111110000101111111111111000000000000000000000001111111111001000000000000000
111110001001111111111111100000000000000000000011111111111001000000000000000
011000011011111111111111100000000000000000000011111111111000000000000000000
110000010111111111111111110000111001111101110111111111111100000000000000000
110000100111111111111111110000111111111101100111111111111100000000000000000
100001001111111111111111111000011111000000001111111111111100000000000000000
100000011111111111111111111000000111100000001111111111111100000000000000000
000000111111111111111111111000000011111100011111111111111100000000000000000
110001111111111111111111111100000000000000011111111111111100000000000000000
110001111111111111111111111100000000000000111111111111111100000000000000000
111011111111111111111111111110000000000000111111111111111100000000000000000
011111111111111111111111111111000000000000111111111111111100000000000000000
000011111111111111111111111111100000000001111111111111111100000000000000000
001001111111111111111111111110000000000000111111111111111100110000000000000
101100111111111111111111111100000000000000000111111111111100001111100000000
111100011111111111111111111111000000000000000011111111111100000011111110000
110001011111111111111111111110000000000000000000111111111100000000111110000
110001101111111111111111111110000000000000000000011111111100000000001110000
100001010111111111111111111110000000000000000000000111111000000000000000000
110001011111111111111111111100000000000000000000000111111000000000000000000
110001101111111111111111111000000000000000000000000011111000000000000000000
111000110111111111111111111000000000000000000000000001111000000000000000000
111000110111111111111111111100000000000000000000000001111000000000000000000

------------- 2 The image with characters -------------
         iiii                                                        bb iii
iiiiiiiii                                                           bbb iii
iiiiiiiii                                                           bbb iii
iiiiiiii                                                            bbb iii
iiiiiii                                                            bbbb iii
iiiiii   ii                                                        bbbb iii
iiiii   ii                                                         bbbb iii
iiii   ii                                                         bbbbb iii
iii   ii                  c                                    d  bbbbb iii
iii  ii           e iiii                                     dd  bbbbbb iii
iiiiii    f         iiii     iiiiiiii                      ddd   bbbbbb iii
iiiiii   f         iiiiii iiiiiiiiii                    ddddd   bbbbbbb   i
  iii             i iiiiiiiiiiiiiii                   ddddd    bbbbbbbb iii
iiii   i       i iiiiiiiiiiiiiiiii                    ddd     bbbbbbbbb  ii
 iii  ii       iiiiiiiiiiiiiiiiii                  gg        bbbbbbbbbb iii
iii  iii i  iiiiiiiiiiiiiiiiiii                  ggg        bbbbbbbbbbb ii 
ii  ii iii iiiiiiiiiiiiiiiiii i                 ggg        bbbbbbbbbbbb iii
iii i  ii  iiiiiiiiiiiiiiiiii i                 gggg      bbbbbbbbbbbbb  ii
 iiii ii iiiiiiiiiiiiiiiiiiiii                   gggg   bbbbbbbbbbbbbb  hii
hiiiii  iiiiiiiiiiiiiiiiiiiiii                   gggg   bbbbbbbbbbbbbb  iii
iiiiii iiiiiiiiiiiiiiiiiiiii                     gggg   bbbbbbbbbbbbb   iii
iiiiiiiiiiiiiiiiiiiiiiiiii                        gggg  bbbbbbbbbbbbb   iii
iii  iiiiiiiiiiiiiiiiiiii                         gggg  bbbbbbbbbbbb    iii
iii  iiiiiiiiiiiiiiii ii                          gggg  bbbbbbbbbbbb    i  
i   iiiiiiiiiiiiiiiiiii                           ggggg bbbbbbbbbbbb    i  
i   iiiiiiiiiiiiiiiiiii                           ggggg bbbbbbbbbbb       i
  iiiiiiiiiiiiiiiiiii i        i                  ggggg bbbbbbbbbbb       i
  iiiiiiiiiiiiiiiiiiii        iiiii               ggggg bbbbbbbbbbb      ii
 iiiiiiiiiiiiiiiiiii             iiii           ggggggg  bbbbbbbbb      iii
iiiiiiiiiiiiiiiiiiii       iiiiiiiiiii        ggggggggg  bbbbbbbbb      iii
iiiiiiiiiiiiiiiiiii       iiiiiiiiii i       ggggggggggg bbbbbbbbb      iii
iiiiiiiiiiiiiiiiii       iiiiiii iiiii      gggggggggggg bbbbbbbb       iii
iiiiiiiiiiiiiiiiii       iiiiiii  iiiii    ggggg ggggggg bbbbbbbb       iii
iiiiiiiiiiiiiiiii       iiiiiii    iiii    g gg  ggggggg bbbbbbbb       iii
iiiiiiiiiiiiiiii       i   iii      iii         gggggggg bbbbbbb        iii
iiiii  iiiiiiiiii     i      ii     iii       gggggggggg bbbbbbb        iii
iiiiii iiiiiiiii    iii               ii       ggggggggg bbbbbbb        iii
iiiiii iiiiiiii    iiii               ii        gggggggg bbbbbbb        iii
iiiii iiiiiiii     iiii               ii        gggggggg  bbbbb         iii
iiiiiii iiiiiii   iiiii                i        gggggggg  bbbbb         iii
iiiiiii  iiii    iiiiii                i        gggggggg  bbbbb         iii
iiiiiiiiiiiiii   iiiiii               ii         ggggggg  bbbb          iii
iiiiiii i ii    iiiiiii               ii        gggggggg  bbbb          iii
iiiiiii iiiii   iiiiiiii              ii         ggggggg  bbbb          iii
iiiii iiiii    iiiiiiiii           ii  i        gggggggg  bbb           iii
iiiiiiiiii    iiiiiiiiii           ii  ii       ggggggggg  bb           iii
iiiii iiii   iiiiiiiiiii           iiiiiii      ggggggggg  bb           iii
iiiiiiiiii   iiiiiiiiiii             iiii      gggggggggg  bb           i i
i iiiii  i  iiiiiiiiiiiii                      gggggggggg  b            iii
iiiii    i iiiiiiiiiiiii                       gggggggggg  b            iii
iiiii   i  iiiiiiiiiiiiii                     ggggggggggg  b             ii
 ii    ii iiiiiiiiiiiiiii                     ggggggggggg               ii 
ii     i iiiiiiiiiiiiiiiii    jjj  jjjjj kkk ggggggggggggg              ii 
ii    i  iiiiiiiiiiiiiiiii    jjjjjjjjjj kk  ggggggggggggg              i  
i    i  iiiiiiiiiiiiiiiiiii    jjjjj        gggggggggggggg              i  
i      iiiiiiiiiiiiiiiiiiii      jjjj       gggggggggggggg                 
      iiiiiiiiiiiiiiiiiiiii       jjjjjj   ggggggggggggggg              ii 
ii   iiiiiiiiiiiiiiiiiiiiiii               ggggggggggggggg              ii 
ii   iiiiiiiiiiiiiiiiiiiiiii              gggggggggggggggg              iii
iii iiiiiiiiiiiiiiiiiiiiiiiii             gggggggggggggggg               ii
 iiiiiiiiiiiiiiiiiiiiiiiiiiiii            gggggggggggggggg                 
    iiiiiiiiiiiiiiiiiiiiiiiiiii          ggggggggggggggggg                l
  l  iiiiiiiiiiiiiiiiiiiiiiii             gggggggggggggggg  mm          l l
l ll  iiiiiiiiiiiiiiiiiiiiii                 ggggggggggggg    mmmmm     lll
llll   iiiiiiiiiiiiiiiiiiiiiii                gggggggggggg      mmmmmmm ll 
ll   i iiiiiiiiiiiiiiiiiiiiii                   gggggggggg        mmmmm ll 
ll   ii iiiiiiiiiiiiiiiiiiiii                    ggggggggg          mmm l  
l    i i iiiiiiiiiiiiiiiiiiii                      gggggg               ll 
ll   i iiiiiiiiiiiiiiiiiiiii                       gggggg               ll 
ll   ii iiiiiiiiiiiiiiiiiii                         ggggg               lll
lll   ii iiiiiiiiiiiiiiiiii                          gggg               lll
lll   ii iiiiiiiiiiiiiiiiiii                         gggg                  

------------- 3 The sorted list of component size -------------
a	  	0
c	  	1
e	  	1
f	  	2
h	  	2
k	  	5
d	  	19
m	  	22
j	  	33
l	  	44
b	  	356
g	  	510
i	  	1652

------------- 4 The image with set size greater than 1-------------
         iiii                                                        bb iii
iiiiiiiii                                                           bbb iii
iiiiiiiii                                                           bbb iii
iiiiiiii                                                            bbb iii
iiiiiii                                                            bbbb iii
iiiiii   ii                                                        bbbb iii
iiiii   ii                                                         bbbb iii
iiii   ii                                                         bbbbb iii
iii   ii                                                       d  bbbbb iii
iii  ii             iiii                                     dd  bbbbbb iii
iiiiii    f         iiii     iiiiiiii                      ddd   bbbbbb iii
iiiiii   f         iiiiii iiiiiiiiii                    ddddd   bbbbbbb   i
  iii             i iiiiiiiiiiiiiii                   ddddd    bbbbbbbb iii
iiii   i       i iiiiiiiiiiiiiiiii                    ddd     bbbbbbbbb  ii
 iii  ii       iiiiiiiiiiiiiiiiii                  gg        bbbbbbbbbb iii
iii  iii i  iiiiiiiiiiiiiiiiiii                  ggg        bbbbbbbbbbb ii 
ii  ii iii iiiiiiiiiiiiiiiiii i                 ggg        bbbbbbbbbbbb iii
iii i  ii  iiiiiiiiiiiiiiiiii i                 gggg      bbbbbbbbbbbbb  ii
 iiii ii iiiiiiiiiiiiiiiiiiiii                   gggg   bbbbbbbbbbbbbb  hii
hiiiii  iiiiiiiiiiiiiiiiiiiiii                   gggg   bbbbbbbbbbbbbb  iii
iiiiii iiiiiiiiiiiiiiiiiiiii                     gggg   bbbbbbbbbbbbb   iii
iiiiiiiiiiiiiiiiiiiiiiiiii                        gggg  bbbbbbbbbbbbb   iii
iii  iiiiiiiiiiiiiiiiiiii                         gggg  bbbbbbbbbbbb    iii
iii  iiiiiiiiiiiiiiii ii                          gggg  bbbbbbbbbbbb    i  
i   iiiiiiiiiiiiiiiiiii                           ggggg bbbbbbbbbbbb    i  
i   iiiiiiiiiiiiiiiiiii                           ggggg bbbbbbbbbbb       i
  iiiiiiiiiiiiiiiiiii i        i                  ggggg bbbbbbbbbbb       i
  iiiiiiiiiiiiiiiiiiii        iiiii               ggggg bbbbbbbbbbb      ii
 iiiiiiiiiiiiiiiiiii             iiii           ggggggg  bbbbbbbbb      iii
iiiiiiiiiiiiiiiiiiii       iiiiiiiiiii        ggggggggg  bbbbbbbbb      iii
iiiiiiiiiiiiiiiiiii       iiiiiiiiii i       ggggggggggg bbbbbbbbb      iii
iiiiiiiiiiiiiiiiii       iiiiiii iiiii      gggggggggggg bbbbbbbb       iii
iiiiiiiiiiiiiiiiii       iiiiiii  iiiii    ggggg ggggggg bbbbbbbb       iii
iiiiiiiiiiiiiiiii       iiiiiii    iiii    g gg  ggggggg bbbbbbbb       iii
iiiiiiiiiiiiiiii       i   iii      iii         gggggggg bbbbbbb        iii
iiiii  iiiiiiiiii     i      ii     iii       gggggggggg bbbbbbb        iii
iiiiii iiiiiiiii    iii               ii       ggggggggg bbbbbbb        iii
iiiiii iiiiiiii    iiii               ii        gggggggg bbbbbbb        iii
iiiii iiiiiiii     iiii               ii        gggggggg  bbbbb         iii
iiiiiii iiiiiii   iiiii                i        gggggggg  bbbbb         iii
iiiiiii  iiii    iiiiii                i        gggggggg  bbbbb         iii
iiiiiiiiiiiiii   iiiiii               ii         ggggggg  bbbb          iii
iiiiiii i ii    iiiiiii               ii        gggggggg  bbbb          iii
iiiiiii iiiii   iiiiiiii              ii         ggggggg  bbbb          iii
iiiii iiiii    iiiiiiiii           ii  i        gggggggg  bbb           iii
iiiiiiiiii    iiiiiiiiii           ii  ii       ggggggggg  bb           iii
iiiii iiii   iiiiiiiiiii           iiiiiii      ggggggggg  bb           iii
iiiiiiiiii   iiiiiiiiiii             iiii      gggggggggg  bb           i i
i iiiii  i  iiiiiiiiiiiii                      gggggggggg  b            iii
iiiii    i iiiiiiiiiiiii                       gggggggggg  b            iii
iiiii   i  iiiiiiiiiiiiii                     ggggggggggg  b             ii
 ii    ii iiiiiiiiiiiiiii                     ggggggggggg               ii 
ii     i iiiiiiiiiiiiiiiii    jjj  jjjjj kkk ggggggggggggg              ii 
ii    i  iiiiiiiiiiiiiiiii    jjjjjjjjjj kk  ggggggggggggg              i  
i    i  iiiiiiiiiiiiiiiiiii    jjjjj        gggggggggggggg              i  
i      iiiiiiiiiiiiiiiiiiii      jjjj       gggggggggggggg                 
      iiiiiiiiiiiiiiiiiiiii       jjjjjj   ggggggggggggggg              ii 
ii   iiiiiiiiiiiiiiiiiiiiiii               ggggggggggggggg              ii 
ii   iiiiiiiiiiiiiiiiiiiiiii              gggggggggggggggg              iii
iii iiiiiiiiiiiiiiiiiiiiiiiii             gggggggggggggggg               ii
 iiiiiiiiiiiiiiiiiiiiiiiiiiiii            gggggggggggggggg                 
    iiiiiiiiiiiiiiiiiiiiiiiiiii          ggggggggggggggggg                l
  l  iiiiiiiiiiiiiiiiiiiiiiii             gggggggggggggggg  mm          l l
l ll  iiiiiiiiiiiiiiiiiiiiii                 ggggggggggggg    mmmmm     lll
llll   iiiiiiiiiiiiiiiiiiiiiii                gggggggggggg      mmmmmmm ll 
ll   i iiiiiiiiiiiiiiiiiiiiii                   gggggggggg        mmmmm ll 
ll   ii iiiiiiiiiiiiiiiiiiiii                    ggggggggg          mmm l  
l    i i iiiiiiiiiiiiiiiiiiii                      gggggg               ll 
ll   i iiiiiiiiiiiiiiiiiiiii                       gggggg               ll 
ll   ii iiiiiiiiiiiiiiiiiii                         ggggg               lll
lll   ii iiiiiiiiiiiiiiiiii                          gggg               lll
lll   ii iiiiiiiiiiiiiiiiiii                         gggg                  

------------- 5 The image with size greater than 11-------------
         iiii                                                        bb iii
iiiiiiiii                                                           bbb iii
iiiiiiiii                                                           bbb iii
iiiiiiii                                                            bbb iii
iiiiiii                                                            bbbb iii
iiiiii   ii                                                        bbbb iii
iiiii   ii                                                         bbbb iii
iiii   ii                                                         bbbbb iii
iii   ii                                                       d  bbbbb iii
iii  ii             iiii                                     dd  bbbbbb iii
iiiiii              iiii     iiiiiiii                      ddd   bbbbbb iii
iiiiii             iiiiii iiiiiiiiii                    ddddd   bbbbbbb   i
  iii             i iiiiiiiiiiiiiii                   ddddd    bbbbbbbb iii
iiii   i       i iiiiiiiiiiiiiiiii                    ddd     bbbbbbbbb  ii
 iii  ii       iiiiiiiiiiiiiiiiii                  gg        bbbbbbbbbb iii
iii  iii i  iiiiiiiiiiiiiiiiiii                  ggg        bbbbbbbbbbb ii 
ii  ii iii iiiiiiiiiiiiiiiiii i                 ggg        bbbbbbbbbbbb iii
iii i  ii  iiiiiiiiiiiiiiiiii i                 gggg      bbbbbbbbbbbbb  ii
 iiii ii iiiiiiiiiiiiiiiiiiiii                   gggg   bbbbbbbbbbbbbb   ii
 iiiii  iiiiiiiiiiiiiiiiiiiiii                   gggg   bbbbbbbbbbbbbb  iii
iiiiii iiiiiiiiiiiiiiiiiiiii                     gggg   bbbbbbbbbbbbb   iii
iiiiiiiiiiiiiiiiiiiiiiiiii                        gggg  bbbbbbbbbbbbb   iii
iii  iiiiiiiiiiiiiiiiiiii                         gggg  bbbbbbbbbbbb    iii
iii  iiiiiiiiiiiiiiii ii                          gggg  bbbbbbbbbbbb    i  
i   iiiiiiiiiiiiiiiiiii                           ggggg bbbbbbbbbbbb    i  
i   iiiiiiiiiiiiiiiiiii                           ggggg bbbbbbbbbbb       i
  iiiiiiiiiiiiiiiiiii i        i                  ggggg bbbbbbbbbbb       i
  iiiiiiiiiiiiiiiiiiii        iiiii               ggggg bbbbbbbbbbb      ii
 iiiiiiiiiiiiiiiiiii             iiii           ggggggg  bbbbbbbbb      iii
iiiiiiiiiiiiiiiiiiii       iiiiiiiiiii        ggggggggg  bbbbbbbbb      iii
iiiiiiiiiiiiiiiiiii       iiiiiiiiii i       ggggggggggg bbbbbbbbb      iii
iiiiiiiiiiiiiiiiii       iiiiiii iiiii      gggggggggggg bbbbbbbb       iii
iiiiiiiiiiiiiiiiii       iiiiiii  iiiii    ggggg ggggggg bbbbbbbb       iii
iiiiiiiiiiiiiiiii       iiiiiii    iiii    g gg  ggggggg bbbbbbbb       iii
iiiiiiiiiiiiiiii       i   iii      iii         gggggggg bbbbbbb        iii
iiiii  iiiiiiiiii     i      ii     iii       gggggggggg bbbbbbb        iii
iiiiii iiiiiiiii    iii               ii       ggggggggg bbbbbbb        iii
iiiiii iiiiiiii    iiii               ii        gggggggg bbbbbbb        iii
iiiii iiiiiiii     iiii               ii        gggggggg  bbbbb         iii
iiiiiii iiiiiii   iiiii                i        gggggggg  bbbbb         iii
iiiiiii  iiii    iiiiii                i        gggggggg  bbbbb         iii
iiiiiiiiiiiiii   iiiiii               ii         ggggggg  bbbb          iii
iiiiiii i ii    iiiiiii               ii        gggggggg  bbbb          iii
iiiiiii iiiii   iiiiiiii              ii         ggggggg  bbbb          iii
iiiii iiiii    iiiiiiiii           ii  i        gggggggg  bbb           iii
iiiiiiiiii    iiiiiiiiii           ii  ii       ggggggggg  bb           iii
iiiii iiii   iiiiiiiiiii           iiiiiii      ggggggggg  bb           iii
iiiiiiiiii   iiiiiiiiiii             iiii      gggggggggg  bb           i i
i iiiii  i  iiiiiiiiiiiii                      gggggggggg  b            iii
iiiii    i iiiiiiiiiiiii                       gggggggggg  b            iii
iiiii   i  iiiiiiiiiiiiii                     ggggggggggg  b             ii
 ii    ii iiiiiiiiiiiiiii                     ggggggggggg               ii 
ii     i iiiiiiiiiiiiiiiii    jjj  jjjjj     ggggggggggggg              ii 
ii    i  iiiiiiiiiiiiiiiii    jjjjjjjjjj     ggggggggggggg              i  
i    i  iiiiiiiiiiiiiiiiiii    jjjjj        gggggggggggggg              i  
i      iiiiiiiiiiiiiiiiiiii      jjjj       gggggggggggggg                 
      iiiiiiiiiiiiiiiiiiiii       jjjjjj   ggggggggggggggg              ii 
ii   iiiiiiiiiiiiiiiiiiiiiii               ggggggggggggggg              ii 
ii   iiiiiiiiiiiiiiiiiiiiiii              gggggggggggggggg              iii
iii iiiiiiiiiiiiiiiiiiiiiiiii             gggggggggggggggg               ii
 iiiiiiiiiiiiiiiiiiiiiiiiiiiii            gggggggggggggggg                 
    iiiiiiiiiiiiiiiiiiiiiiiiiii          ggggggggggggggggg                l
  l  iiiiiiiiiiiiiiiiiiiiiiii             gggggggggggggggg  mm          l l
l ll  iiiiiiiiiiiiiiiiiiiiii                 ggggggggggggg    mmmmm     lll
llll   iiiiiiiiiiiiiiiiiiiiiii                gggggggggggg      mmmmmmm ll 
ll   i iiiiiiiiiiiiiiiiiiiiii                   gggggggggg        mmmmm ll 
ll   ii iiiiiiiiiiiiiiiiiiiii                    ggggggggg          mmm l  
l    i i iiiiiiiiiiiiiiiiiiii                      gggggg               ll 
ll   i iiiiiiiiiiiiiiiiiiiii                       gggggg               ll 
ll   ii iiiiiiiiiiiiiiiiiii                         ggggg               lll
lll   ii iiiiiiiiiiiiiiiiii                          gggg               lll
lll   ii iiiiiiiiiiiiiiiiiii                         gggg                  

]0;dxie32@compute:~/cs3340/asn2[?2004h[dxie32@compute asn2]$ exit
[?2004lexit

Script done on 2023-03-02 19:29:23-05:00 [COMMAND_EXIT_CODE="0"]
